main: com.gmail.St3venAU.plugins.ArmorStandTools.AST
name: ArmorStandTools
version: ${project.version}
api-version: 1.21
author: St3venAU
description: Armor stand manipulation tools
softdepend: [WorldGuard, SquidSkyblock]
