main: io.squid.armorstandtools.AST
name: ArmorStandTools
version: ${project.version}
api-version: 1.21
author: St3venAU, JeSuisTrolls
description: Armor stand manipulation tools
softdepend: [WorldGuard, SquidSkyblock]
